// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfusqoiczhzpaagchbnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmdXNxb2ljemh6cGFhZ2NoYm5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDkxODQsImV4cCI6MjA2NjI4NTE4NH0.oVcvNpvjYS_rTI7_ViITXa69NZKWCOqY_zNseG7B3ds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});